/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "depositservice_constants.h"



const depositserviceConstants g_depositservice_constants;

depositserviceConstants::depositserviceConstants() {
}



