/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef depositservice_TYPES_H
#define depositservice_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class DepositResult;

typedef struct _DepositResult__isset {
  _DepositResult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _DepositResult__isset;

class DepositResult : public virtual ::apache::thrift::TBase {
 public:

  DepositResult(const DepositResult&);
  DepositResult& operator=(const DepositResult&);
  DepositResult() : success(0), error() {
  }

  virtual ~DepositResult() throw();
  bool success;
  std::string error;

  _DepositResult__isset __isset;

  void __set_success(const bool val);

  void __set_error(const std::string& val);

  bool operator == (const DepositResult & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const DepositResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DepositResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(DepositResult &a, DepositResult &b);

inline std::ostream& operator<<(std::ostream& out, const DepositResult& obj)
{
  obj.printTo(out);
  return out;
}



#endif
