/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef depositservice_CONSTANTS_H
#define depositservice_CONSTANTS_H

#include "depositservice_types.h"



class depositserviceConstants {
 public:
  depositserviceConstants();

};

extern const depositserviceConstants g_depositservice_constants;



#endif
