/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dynamodb_client_constants.h"



const dynamodb_clientConstants g_dynamodb_client_constants;

dynamodb_clientConstants::dynamodb_clientConstants() {
}



