/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sendmail_constants.h"



const sendmailConstants g_sendmail_constants;

sendmailConstants::sendmailConstants() {
}



