/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef emailalertservice_TYPES_H
#define emailalertservice_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class EmailAlertResult;

typedef struct _EmailAlertResult__isset {
  _EmailAlertResult__isset() : success(false), error(false) {}
  bool success :1;
  bool error :1;
} _EmailAlertResult__isset;

class EmailAlertResult : public virtual ::apache::thrift::TBase {
 public:

  EmailAlertResult(const EmailAlertResult&);
  EmailAlertResult& operator=(const EmailAlertResult&);
  EmailAlertResult() : success(0), error() {
  }

  virtual ~EmailAlertResult() throw();
  bool success;
  std::string error;

  _EmailAlertResult__isset __isset;

  void __set_success(const bool val);

  void __set_error(const std::string& val);

  bool operator == (const EmailAlertResult & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const EmailAlertResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EmailAlertResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(EmailAlertResult &a, EmailAlertResult &b);

inline std::ostream& operator<<(std::ostream& out, const EmailAlertResult& obj)
{
  obj.printTo(out);
  return out;
}



#endif
